import 'dotenv/config'
import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../src/generated/prisma'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

const figures = [
  {
    slug: 'son-goku-saiyan-raised-on-earth',
    name: 'Son Goku -Saiyan Raised on Earth-',
    character: 'Son Goku',
    series: 'Dragon Ball Z',
    arc: 'Saiyan Saga',
    releaseDate: new Date('2013-09-28'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: 'The iconic Son Goku in his classic orange gi, featuring multiple expression plates and interchangeable hands.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Power pole', 'Flying Nimbus'],
    images: [],
  },
  {
    slug: 'son-goku-super-saiyan',
    name: 'Son Goku Super Saiyan',
    character: 'Son Goku',
    series: 'Dragon Ball Z',
    arc: 'Frieza Saga',
    releaseDate: new Date('2014-06-28'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan',
    description: 'Son Goku in his first Super Saiyan transformation with golden hair effect parts.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Kamehameha effect parts', 'Aura effect parts'],
    images: [],
  },
  {
    slug: 'son-goku-super-saiyan-god',
    name: 'Son Goku Super Saiyan God',
    character: 'Son Goku',
    series: 'Dragon Ball Super',
    arc: 'Battle of Gods',
    releaseDate: new Date('2014-12-20'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan God',
    description: 'Goku in his divine Super Saiyan God form with red hair and aura effect parts.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Aura effect parts'],
    images: [],
  },
  {
    slug: 'son-goku-super-saiyan-blue',
    name: 'Son Goku Super Saiyan Blue',
    character: 'Son Goku',
    series: 'Dragon Ball Super',
    arc: 'Resurrection F',
    releaseDate: new Date('2015-08-29'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan Blue',
    description: 'Goku as Super Saiyan Blue (SSGSS) with blue hair and godly ki aura.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Kamehameha effect parts', 'Blue aura parts'],
    images: [],
  },
  {
    slug: 'son-goku-ultra-instinct',
    name: 'Son Goku -Ultra Instinct-',
    character: 'Son Goku',
    series: 'Dragon Ball Super',
    arc: 'Tournament of Power',
    releaseDate: new Date('2018-07-28'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Ultra Instinct',
    description: 'Goku in his mastered Ultra Instinct form with silver hair and divine aura.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Silver aura parts', 'Ki blade effect parts'],
    images: [],
  },
  {
    slug: 'son-goku-ultra-instinct-omen',
    name: 'Son Goku -Ultra Instinct "Omen"-',
    character: 'Son Goku',
    series: 'Dragon Ball Super',
    arc: 'Tournament of Power',
    releaseDate: new Date('2018-04-28'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Ultra Instinct Omen',
    description: "Goku's incomplete Ultra Instinct form with grey-tipped hair.",
    accessories: ['3x expression plates', '6x interchangeable hands', 'Grey aura effect parts', 'Ki blast effects'],
    images: [],
  },
  {
    slug: 'vegeta-scouter',
    name: 'Vegeta -Scouter-',
    character: 'Vegeta',
    series: 'Dragon Ball Z',
    arc: 'Saiyan Saga',
    releaseDate: new Date('2013-11-30'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Scouter',
    description: 'Prince Vegeta in his Saiyan saga armor with scouter accessory.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Scouter', 'Galick Gun effect parts'],
    images: [],
  },
  {
    slug: 'vegeta-super-saiyan',
    name: 'Vegeta Super Saiyan',
    character: 'Vegeta',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2014-09-27'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan',
    description: 'Vegeta in his Super Saiyan form with golden hair.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Final Flash effect parts', 'Aura parts'],
    images: [],
  },
  {
    slug: 'vegeta-super-saiyan-blue',
    name: 'Vegeta Super Saiyan Blue',
    character: 'Vegeta',
    series: 'Dragon Ball Super',
    arc: 'Resurrection F',
    releaseDate: new Date('2016-03-26'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan Blue',
    description: 'Vegeta in Super Saiyan Blue form, ready for battle.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Final Flash effect parts', 'Blue aura parts'],
    images: [],
  },
  {
    slug: 'frieza-first-form',
    name: 'Frieza -First Form-',
    character: 'Frieza',
    series: 'Dragon Ball Z',
    arc: 'Frieza Saga',
    releaseDate: new Date('2014-04-26'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'First Form',
    description: 'Frieza in his iconic first form with hover pod.',
    accessories: ['3x expression plates', '4x interchangeable hands', 'Hover pod', 'Death beam effect part'],
    images: [],
  },
  {
    slug: 'frieza-final-form',
    name: 'Frieza -Final Form-',
    character: 'Frieza',
    series: 'Dragon Ball Z',
    arc: 'Frieza Saga',
    releaseDate: new Date('2014-08-30'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Final Form',
    description: 'Frieza in his terrifying final form.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Death ball effect parts', 'Tail swap parts'],
    images: [],
  },
  {
    slug: 'golden-frieza',
    name: 'Golden Frieza',
    character: 'Frieza',
    series: 'Dragon Ball Super',
    arc: 'Resurrection F',
    releaseDate: new Date('2015-12-26'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Golden',
    description: 'Frieza in his ultimate Golden form from Resurrection F.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Death beam effect parts', 'Golden aura parts'],
    images: [],
  },
  {
    slug: 'cell-perfect-form',
    name: 'Cell -Perfect Form-',
    character: 'Cell',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2015-03-28'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Perfect Form',
    description: 'The perfect bio-android Cell in his completed form.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Solar Kamehameha effect parts', 'Energy disc'],
    images: [],
  },
  {
    slug: 'cell-semi-perfect-form',
    name: 'Cell -Semi-Perfect Form-',
    character: 'Cell',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2016-08-27'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: true,
    isRerelease: false,
    version: 'Semi-Perfect Form',
    description: 'Cell in his intermediate semi-perfect form after absorbing Android 17.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Energy blast effects', 'Absorption tail'],
    images: [],
  },
  {
    slug: 'gohan-super-saiyan-2',
    name: 'Son Gohan Super Saiyan 2',
    character: 'Son Gohan',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2015-06-27'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan 2',
    description: 'Teen Gohan awakening his latent power in the Cell Games.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Father-Son Kamehameha effect parts', 'Lightning effect parts'],
    images: [],
  },
  {
    slug: 'gohan-ultimate',
    name: 'Son Gohan -Ultimate-',
    character: 'Son Gohan',
    series: 'Dragon Ball Z',
    arc: 'Buu Saga',
    releaseDate: new Date('2017-09-30'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Ultimate',
    description: 'Ultimate Gohan with his full potential unlocked by Elder Kai.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Masenko effect parts'],
    images: [],
  },
  {
    slug: 'piccolo',
    name: 'Piccolo',
    character: 'Piccolo',
    series: 'Dragon Ball Z',
    arc: 'Saiyan Saga',
    releaseDate: new Date('2014-02-22'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: 'Piccolo, the Namekian warrior in his classic outfit.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Special Beam Cannon effect', 'Removable turban and cape'],
    images: [],
  },
  {
    slug: 'future-trunks-super-saiyan',
    name: 'Future Trunks Super Saiyan',
    character: 'Future Trunks',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2015-09-26'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan',
    description: 'Future Trunks from the alternate timeline in Super Saiyan form with his signature sword.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Sword', 'Sheath', 'Burning Attack effect'],
    images: [],
  },
  {
    slug: 'trunks-ssj-dbs',
    name: 'Future Trunks Super Saiyan (DBS)',
    character: 'Future Trunks',
    series: 'Dragon Ball Super',
    arc: 'Future Trunks Arc',
    releaseDate: new Date('2017-03-25'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan DBS',
    description: 'Future Trunks as seen in Dragon Ball Super with his new sword and blue-tinted SSJ hair.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'New Sword', 'Sword effect parts', 'Galick Gun effect'],
    images: [],
  },
  {
    slug: 'beerus',
    name: 'Beerus',
    character: 'Beerus',
    series: 'Dragon Ball Super',
    arc: 'Battle of Gods',
    releaseDate: new Date('2015-11-28'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: 'The God of Destruction Beerus with his divine power.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Sphere of Destruction effect parts', 'Energy orb'],
    images: [],
  },
  {
    slug: 'whis',
    name: 'Whis',
    character: 'Whis',
    series: 'Dragon Ball Super',
    arc: 'Battle of Gods',
    releaseDate: new Date('2016-01-30'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: "Beerus's angel attendant Whis with his staff.",
    accessories: ['3x expression plates', '6x interchangeable hands', "Whis's staff", 'Angel aura parts'],
    images: [],
  },
  {
    slug: 'broly-legendary-super-saiyan',
    name: 'Broly -Legendary Super Saiyan-',
    character: 'Broly',
    series: 'Dragon Ball Z',
    arc: 'Movie',
    releaseDate: new Date('2016-10-29'),
    msrp: 64.99,
    msrpJpy: 7000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Legendary Super Saiyan',
    description: 'The Legendary Super Saiyan Broly from the Z-era films.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Eraser Cannon effect parts', 'Omega Blaster parts'],
    images: [],
  },
  {
    slug: 'broly-dbs',
    name: 'Broly (DBS)',
    character: 'Broly',
    series: 'Dragon Ball Super',
    arc: 'Broly Movie',
    releaseDate: new Date('2019-05-25'),
    msrp: 64.99,
    msrpJpy: 7000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'DBS Original',
    description: 'The rebooted Broly from Dragon Ball Super: Broly with his Wrathful form.',
    accessories: ['3x expression plates', '8x interchangeable hands', 'Aura effect parts', 'Wrathful transformation parts'],
    images: [],
  },
  {
    slug: 'android-18',
    name: 'Android 18',
    character: 'Android 18',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2016-07-30'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: 'The powerful Android 18 in her classic blue jacket outfit.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Energy blast effect parts'],
    images: [],
  },
  {
    slug: 'android-17',
    name: 'Android 17',
    character: 'Android 17',
    series: 'Dragon Ball Z',
    arc: 'Cell Saga',
    releaseDate: new Date('2017-02-25'),
    msrp: 49.99,
    msrpJpy: 5500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: 'Android 17 in his classic outfit, twin of Android 18.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Energy barrier effect parts'],
    images: [],
  },
  {
    slug: 'krillin',
    name: 'Krillin',
    character: 'Krillin',
    series: 'Dragon Ball Z',
    arc: 'Frieza Saga',
    releaseDate: new Date('2016-04-30'),
    msrp: 44.99,
    msrpJpy: 5000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: "Earth's Strongest Man, Krillin, with his Destructo Disc.",
    accessories: ['3x expression plates', '6x interchangeable hands', 'Destructo Disc effect parts', 'Senzu beans pouch'],
    images: [],
  },
  {
    slug: 'majin-buu-pure',
    name: 'Majin Buu -Pure-',
    character: 'Majin Buu',
    series: 'Dragon Ball Z',
    arc: 'Buu Saga',
    releaseDate: new Date('2017-06-24'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Pure',
    description: 'Pure Majin Buu, the childlike but terrifyingly powerful pink menace.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'Candy beam effect', 'Chocolate bar prop'],
    images: [],
  },
  {
    slug: 'hit',
    name: 'Hit',
    character: 'Hit',
    series: 'Dragon Ball Super',
    arc: 'Universe 6 Arc',
    releaseDate: new Date('2017-04-29'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: "Universe 6's legendary assassin Hit, master of Time-Skip.",
    accessories: ['3x expression plates', '6x interchangeable hands', 'Time-Skip effect parts'],
    images: [],
  },
  {
    slug: 'jiren',
    name: 'Jiren',
    character: 'Jiren',
    series: 'Dragon Ball Super',
    arc: 'Tournament of Power',
    releaseDate: new Date('2018-11-24'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Original',
    description: "Universe 11's Pride Trooper Jiren, strongest mortal in the multiverse.",
    accessories: ['3x expression plates', '6x interchangeable hands', 'Power Impact effect parts', 'Ki aura parts'],
    images: [],
  },
  {
    slug: 'goku-black',
    name: 'Goku Black',
    character: 'Goku Black',
    series: 'Dragon Ball Super',
    arc: 'Future Trunks Arc',
    releaseDate: new Date('2017-08-26'),
    msrp: 54.99,
    msrpJpy: 6000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Base',
    description: "Zamasu inhabiting Goku's body, Goku Black with his signature Rose ki.",
    accessories: ['3x expression plates', '6x interchangeable hands', 'Ki Scythe effect parts', 'Black Rose aura'],
    images: [],
  },
  {
    slug: 'goku-black-super-saiyan-rose',
    name: 'Goku Black -Super Saiyan Ros\u00e9-',
    character: 'Goku Black',
    series: 'Dragon Ball Super',
    arc: 'Future Trunks Arc',
    releaseDate: new Date('2018-01-27'),
    msrp: 59.99,
    msrpJpy: 6500,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan Ros\u00e9',
    description: 'Goku Black in his divine Super Saiyan Ros\u00e9 form.',
    accessories: ['3x expression plates', '6x interchangeable hands', 'God Slicer effect parts', 'Pink Rose aura'],
    images: [],
  },
  {
    slug: 'vegito-super-saiyan-blue',
    name: 'Vegito Super Saiyan Blue',
    character: 'Vegito',
    series: 'Dragon Ball Super',
    arc: 'Future Trunks Arc',
    releaseDate: new Date('2018-03-24'),
    msrp: 64.99,
    msrpJpy: 7000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan Blue',
    description: 'The Potara fusion of Goku and Vegeta in Super Saiyan Blue form.',
    accessories: ['3x expression plates', '8x interchangeable hands', 'Kamehameha effect', 'Final Kamehameha effect', 'Potara earrings'],
    images: [],
  },
  {
    slug: 'gogeta-super-saiyan-blue',
    name: 'Gogeta Super Saiyan Blue',
    character: 'Gogeta',
    series: 'Dragon Ball Super',
    arc: 'Broly Movie',
    releaseDate: new Date('2019-07-27'),
    msrp: 64.99,
    msrpJpy: 7000,
    isWebExclusive: false,
    isRerelease: false,
    version: 'Super Saiyan Blue',
    description: 'The fusion dance result of Goku and Vegeta in SSGSS form from DBS: Broly.',
    accessories: ['3x expression plates', '8x interchangeable hands', 'Stardust Breaker effect parts', 'Blue aura'],
    images: [],
  },
]

async function main() {
  console.log('Seeding Dragon Ball SHF figures...')

  for (const figure of figures) {
    await prisma.figure.upsert({
      where: { slug: figure.slug },
      update: figure,
      create: figure,
    })
    console.log(`  \u2713 ${figure.name}`)
  }

  console.log(`\nSeeded ${figures.length} figures.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
